= Memories

:source-highlighter: highlight.js
:source-language: riscvasm

In `virt.lds` we add two symbols (one of them a bit redundant): `__global_pointer$` and `__stack_pointer$`. The latter we use to initialise the `sp` register. The former I think has something to do with optimisation of memory access (i.e. how many offset bits are needed in some operations), but for the moment I'm quite happy to just load a pseudo-rationally selected value.

I also added a helper function `write_register` that (surprisingly) writes the contents of `a0` to the UART. This function should be separated into a `hex_string_from_value` function and a call to `write_string` once memory allocation is solved.

== Allocation

With `sp` set and information regarding where the data segments end we can start looking at a way of managing that memory.

=== Keeping track of stuff

We want to waste as little as possible of the available memory, but we still need to keep track of where the allocated blocks are. We also don't want to go weirdly complex in our first attempt. So we will (for the time being) ignore alignments and stick to a linear algorithm. Every allocation will have at least one byte of metadata. The first bit indicates if the block has been released or if it is still in use. Then follows a Huffman inspired coding of the number of bits in the allocation size field.

So `f1xx xxxx` would indicate that the metadata byte contains the size field and that it can allocate up to 64 bytes. (If we realise that allocations of 1 - 64 quads are more common we can change to that later.)
